#!/bin/bash

usage() { echo "Usage: -f file [-rid] [-h]" 1>&2; exit 1; } 

hasinput=0
hasfile=0
del=0
while getopts ":hdrf:i:" op; do
    case "${op}" in
        f)
            file=${OPTARG}
            hasfile=1
        ;;
        r)
            run=1
        ;;
        i)
            hasinput=1
            input=${OPTARG}
        ;;
        d)
            del=1
        ;;
        h)
            echo "-f file: file to be compiled"
            echo "-r: Optional. execution after compiled"
            echo "-i: Optional. input file"
            echo "-h: This message"
            exit
        ;;
        *)
            usage
        ;;
    esac
done

shift $((OPTIND-1))

if [ "${hasfile}" = 0 ];then
    usage
fi

echo "${file}"

cd compiler
make
./compiler ../${file}


cd ../jasmin
java -jar jasmin.jar ../compiler/output.j

if [ "${run}" = 1 ];then
    echo ""
    echo "******************************************************************************"
    echo "*                                Result                                      *"
    echo "******************************************************************************"
    echo ""
    
    if [ "${hasinput}" = 1 ]; then
        java output < ${input}
    else
        java output
    fi
fi

if [ "${del}" = 1 ];then
    cd ../compiler/
    make clean
    cd ../jasmin/
    rm -f *.class
fi
